#!/usr/bin/env sh

# Check if package.json changed
if git diff-tree -r --name-only --no-commit-id ORIG_HEAD HEAD | grep --quiet "^package.json"; then
  echo "📦 package.json changed. Running npm install..."
  npm install
fi
